## Define churn  -> churn = churn_flag in subscriptions 
# churn_label = 1 if account exists in churn_events OR churn_flag == True
# else 0

# ---- Useful Github actions ---- #
# git status
# git add .
# git commit -m ""
# git push origin main

import pandas as pd
import numpy as np

# Load data - Pull raw SaaS data from CSV files
subscriptions = pd.read_csv("ravenstack_subscriptions.csv") # Subscription details - start date, end date, churn flag
churn_events = pd.read_csv("ravenstack_churn_events.csv") # When customer left and why
accounts = pd.read_csv("ravenstack_accounts.csv")  # Account details


# Build churn label
churned_from_events = churn_events["account_id"].unique() # Creates a list of all accounts that ever churned according to the churn events table.
subscriptions["churn_label"] = subscriptions["churn_flag"].astype(int) # Convert churn_flag to integer (1 for True, 0 for False)
# Overide rule, if an account is in the churn_events, it should be labeled as churned (1) regardless of the churn_flag in subscriptions.
subscriptions["churn_label"] = np.where(
    subscriptions["account_id"].isin(churned_from_events),
    1,
    subscriptions["churn_label"]
)


# Aggregate churn label at the account level
sub_agg = subscriptions.groupby("account_id").agg({
    "seats": "mean", # Typical team size
    "mrr_amount": "sum", # Total revenue generated by the account
    "arr_amount": "sum", # Annualized revenue
    "is_trial": "max", # If the account ever had a trial, this will be 1, otherwise 0
    "upgrade_flag": "max", # If the account ever upgraded, this will be 1, otherwise 0
    "downgrade_flag": "max", # If the account ever downgraded, this will be 1, otherwise 0
    "churn_label": "max" # If the account ever churned, this will be 1, otherwise 0
}).reset_index()



df = accounts.merge(sub_agg, on="account_id", how="left") # Merge account details with aggregated subscription data
print(df.columns)


# clean data - Handle missing values by filling them with appropriate values (median for seats, 0 for revenue)
df["seats"] = df["seats_y"].fillna(df["seats_y"].median()) # use subscription derived seats, fill missing with median
df["mrr_amount"] = df["mrr_amount"].fillna(0)
df["arr_amount"] = df["arr_amount"].fillna(0)


# One-hot encode categorical variables into 0/1 indicators (industry, region)
df = pd.get_dummies(df, columns=["industry", "country", "plan_tier", "referral_source"], drop_first=True)

# x = training data, y = target variable (churn_label)
X = df.drop(columns=["churn_label", "account_id", "account_name", "signup_date"]) # Drop non-predictive columns/target vars
y = df["churn_label"]

X = X.select_dtypes(include=[np.number]) # remove any remaining non numeric columns

# Train/test split
from sklearn.model_selection import train_test_split
# 80/20 split, 80 training, 20 testing, set seed to 42, stratify
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# model training
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)


# model evaluation TPR/FPR, ROC-AUC, classification report (precision, recall, f1-score)
from sklearn.metrics import roc_auc_score, classification_report
# Predict probabilities for the positive class (churn = 1) and convert to binary predictions using a threshold of 0.5
probs = model.predict_proba(X_test)[:, 1]
preds = (probs >= 0.5).astype(int) 
print("ROC-AUC:", roc_auc_score(y_test, probs))
print(classification_report(y_test, preds)) 

print(y_train.value_counts(normalize=True))

print(pd.Series(preds).value_counts(normalize=True))